version: '2'
services:
  app:
    image: dev_games
    command: bash -c "RAILS_ENV=development bundle exec rake db:create db:migrate && RAILS_ENV=development bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: games_app
    tty: true
    stdin_open: true
    environment:
      - DOCKER_DB_HOST=my_postgres
      - POSTGRES_PASSWORD=password
      - DOCKER_IP=172.18.0.1
    volumes:
      - ../games:/myapp
    ports:
      - "3000:3000"
    links:
      - db
      - mail_server
    depends_on:
      - db
      - mail_server
    networks:
      default:
        aliases:
          - dev.games.com
  mail_server:
    image: djfarrelly/maildev
    container_name: pwpr_mail
    ports:
      - "1080:80"
      - "1025:25"
  db:
    image: postgres:11
    container_name: my_postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata:
